const constants ={
    DASHBOARD : 'DASHBOARD',
	GOOGLE : 'GOOGLE',
	YAHOO : 'YAHOO',
	BING : 'BING',
	ASK : 'ASK',
	REGISTER : 'REGISTER',
	LOGIN :'LOGIN',
	SEARCH_KEY : 'SEARCH_KEY',
	KEYWORDS :'KEYWORDS',
	SEARCH_HISTORY : 'SEARCH_HISTORY'
}

export default constants;